### ISSUE TITLE
Help Wanted to generate meeting link for multiple users.

### ISSUE THREAD

**Issue by anonymous21155** [microsoft/MicrosoftCloud#28]
Is it possible to generate meeting link for multiple teams' users at a time? What needs to be done achieve this? Can someone help me on this.

**Comment by DanWahlin** [comment]
The Microsoft Graph `events` API allows an array of `attendees` to be passed. You can find more details in the documentation for that API here:

https://learn.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=javascript#request
