### ISSUE TITLE
Is it possible to generate chat threadID with acs token in the server side?

### ISSUE THREAD

**Issue by Author1212** [microsoft/MicrosoftCloud#29]
I am interested in generating chat threadID with the help of generated ACS token in the server side and the pass this to client side so that the user in the custom app can also chat with Microsoft Team's user. Is this possible? Any guidance on this? Thanks in advance.

**Comment by tomaschladek** [comment]
Hi, you can't use Azure Communication Services to:
- start a chat to users in Teams. 
- chat as Teams user. You can use Graph API for this scenario.
If you would like to do the first scenario, then you can build Teams chat bot, that relays messages from ACS to Teams. Example: ACS user starts a chat to the bot (ACS user). Bot receives the message and sends it to the Teams user. If you would like to do the second scenario, use Graph API to send and receive messages as Microsoft 365 user.

Please let me know if there is anything else I can help with.
