### ISSUE TITLE
Generate meeting gives error "Code: MailboxNotEnabledForRESTAPI Message: The mailbox is either inactive, soft-deleted, or is hosted on-premise."

### ISSUE THREAD

**Issue by umesh23** [microsoft/MicrosoftCloud#41]
https://github.com/microsoft/MicrosoftCloud/blob/3531278fed23d8c16583316bb2c837fcf1629cf0/samples/acs-to-teams-meeting/server/csharp/GraphACSFunctions/Services/GraphService.cs#L20

**Comment by DanWahlin** [comment]
It sounds like the user that was configured in the .env file may not have a valid mailbox. Make sure that the user is part of your Microsoft 365 developer tenant (the steps to get the user info are shown in the tutorial - https://learn.microsoft.com/en-us/microsoft-cloud/dev/tutorials/acs-to-teams-meeting?tabs=csharp%2Cbash&tutorial-step=3).

**Comment by DanWahlin** [comment]
Closing since there hasn't been any activity (and the codebase has been updated since this was posted). Feel free to reopen if you're still having a problem.
