### ISSUE TITLE
Error in MicrosoftCloud\samples\acs-to-teams-meeting\server\typescript> func start

### ISSUE THREAD

**Issue by CornerstoneII** [microsoft/MicrosoftCloud#44]
No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
It appears there's a missing **function.json** file which has been deleted since this is a new codebase recently updated (2 months ago) it is different now. I know this because I have the older codebase on my local machine which runs fine.

Cc @DanWahlin

**Comment by DanWahlin** [comment]
The latest version of the code uses Azure Functions v4 so there won't be a function.json file. I tried running the APIs in a Codespace and it seems to load as expected. 

I'm wondering if there could be an outdated package in your server/typescript directory? You might try updating your Azure Functions core tools (run `func --version` to see if you're on version 4), removing node_modules and package-lock.json, and running npm install again to see if you still get the same issue.

**Comment by CornerstoneII** [comment]
****

> The latest version of the code uses Azure Functions v4 so there won't be a function.json file. I tried running the APIs in a Codespace and it seems to load and run as expected.
> 
> I'm wondering if there could be an outdated package in your server/typescript directory? You might try updating your Azure Functions core tools (run `func --version` to see if you're on version 4), removing node_modules and package-lock.json, and running npm install again to see if you still get the same issue.

Thanks alot your response @DanWahlin, I followed the suggestion you provided but that as well did not work. Please see image below:

<img width="811" alt="image" src="https://github.com/microsoft/MicrosoftCloud/assets/42003510/4700e6bf-63db-412c-a6ae-4a05ceaf137f">

**Comment by DanWahlin** [comment]
Do you have your local.settings.json file in place? Guessing you do, but can’t tell from the image.

**Comment by CornerstoneII** [comment]
> Do you have your local.settings.json file in place? Guessing you do, but can’t tell from the image.

Yes sir I have that in place. I have followed the steps in the documentation and I also automated the entire process before this change.
I am trying to update the az cli version maybe that could be the issue?

**Comment by CornerstoneII** [comment]
No luck.

**Comment by CornerstoneII** [comment]
@DanWahlin does or how can this solution support multiple agents? I was making adjustments by trying to allow for multiple agents that's the root cause for the issues earlier reported.

**Comment by DanWahlin** [comment]
Can you clarify what you mean by "multiple agents"? I'm trying to understand how that ties into the `func start` issue or if you're referring to something else.

**Comment by CornerstoneII** [comment]
@DanWahlin concerning multiple agents, I have resolved that thank you. However, when I publish my functions to a function app they dont appear under the function app.

**Comment by DanWahlin** [comment]
Glad you got that part resolved. As far as publishing the function, it's hard to say without knowing more details. If you can provide more information there we can try to help.

//cc @aycabas

**Comment by CornerstoneII** [comment]
@DanWahlin @aycabas 

**Issue Summary:**

I am experiencing an issue where functions are not appearing in my Azure function app after deployment. Despite successfully navigating to the correct project directory and executing the build and publish commands without errors, the functions do not show up in the Azure portal under the "Functions" section of the function app.

**Details:**

Project Directory: I have verified that I am in the correct directory containing the function app's files.
<img width="477" alt="image" src="https://github.com/microsoft/MicrosoftCloud/assets/42003510/9f50d315-421c-4ced-9dbc-a06b98dd29e4">

Build Process: The command npm run build completes successfully and the expected output files are present in the build directory.
<img width="487" alt="image" src="https://github.com/microsoft/MicrosoftCloud/assets/42003510/0f70a217-df73-4531-a91f-9f13421a5e5b">


Publish Process: I use func azure functionapp publish $appName --verbose for deployment. The command executes without error messages and indicates a successful deployment, but the functions still do not appear in the portal.
<img width="1431" alt="image" src="https://github.com/microsoft/MicrosoftCloud/assets/42003510/5d8b83e8-ed08-4892-b34f-10d094868b12">


Function Runtime: I am using the same runtime version both locally and in Azure.
<img width="507" alt="image" src="https://github.com/microsoft/MicrosoftCloud/assets/42003510/1995f70a-40ea-4c68-af1f-8955f2dd4852">

Permissions and Settings: I have the necessary permissions for deployment and have checked that there are no obvious misconfigurations with triggers or extensions.

<img width="509" alt="image" src="https://github.com/microsoft/MicrosoftCloud/assets/42003510/30f8002b-9fd5-4422-82aa-a3086725e4ec">

<img width="498" alt="image" src="https://github.com/microsoft/MicrosoftCloud/assets/42003510/854d1924-40ab-44ab-8649-79ac9043cf3a">

<img width="254" alt="image" src="https://github.com/microsoft/MicrosoftCloud/assets/42003510/ecdbac5e-5d2c-4fc6-a4af-1a62cfb2459d">

Expected Outcome (Running Locally):

<img width="480" alt="image" src="https://github.com/microsoft/MicrosoftCloud/assets/42003510/5f87b921-e936-4ad8-8578-7bd28cf9f2cc">

**Comment by DanWahlin** [comment]
Thanks for the details and screenshots. I haven't used the func...publish feature lately so I'm not sure on that. Have you tried creating a default project and publishing it to see if you can duplicate the behavior you're seeing? Normally when I experience these types of issues I'll go back to basics and see if something else is involved. You might try going through these steps and seeing if a basic project can be deployed or not to better understand if there's another issue at play:

https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=macos%2Cisolated-process%2Cnode-v4%2Cpython-v2%2Chttp-trigger%2Ccontainer-apps&pivots=programming-language-typescript
